[package]
name = "riff-daw"
version = "0.1.0"
edition = "2024"

[dependencies]
masonry = "0.4.0"
masonry_core = "0.4.0"
masonry_winit = "0.4.0"
xilem = "0.4.0"
xilem_core = "0.4.0"
tracing = "0.1.41"
vello = "0.6.0"
vello_svg = "0.8.0"
image = "0.25.8"
rtrb = "0.2"
raw-window-handle = "0.4"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = { version = "1.0.73", features = ["preserve_order"] }
cairo-rs = "0.14.9"
jack = "0.10.0"
rb = "0.4.1"
vst = { path = "../lib/vst-rs" }
simple-clap-host-helper-lib = { path = "../lib/simple-clap-host-helper-lib" }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
thread-priority = "0.7.0"
base64 = "0.22.1"
regex = "1.5.5"
apres = "0.3.1"
itertools = "0.10.2"
flexi_logger = {version = "0.25.1", features=["async"]}
log = { version="0.4.17",  features = ["release_max_level_off"]}
factor = "0.4.0"
wav_io = "0.1.8"
mlua = { version = "0.8.3", features = ["lua54", "vendored", "macros"] }
sndfile = "0.1.1"
samplerate-rs = "0.1.0"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
indexmap = "1.9.1"
dirs = "4.0.0"
rust-lzma = "0.5.1"
chrono = "0.4.23"
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision"] }
clap-sys = { git = "https://github.com/robbert-vdh/clap-sys.git", rev = "f217cca4f41d4997bf23b06477765a809fa07c34" }
strum = "0.24.1"
strum_macros = "0.24.1"
pathsearch = "0.2.0"
tikv-jemallocator = "0.5.0"
geo = "0.26.0"
state = "0.6.0"
cxx = "1.0.136"
widestring = "1.1.0"
rayon = "1.10.0"
xcb = "1.7.0"
rfd = "0.17.2"
audrey = "0.3.0" #reads/writes multiple audio file formats
vst3-host = "0.5.0"
dawproject = "0.11.0"

[dev-dependencies]
masonry = { version = "0.4.0", features = ["testing"] }


[build-dependencies]
cxx-build = "1.0.136"

[profile.dev]
opt-level = 0
# One debuginfo file per dependency, to reduce file size of tests/examples.
# Note that this value is not supported on Windows.
# See https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo
split-debuginfo="unpacked"

[profile.release]
codegen-units = 1
lto = true
# lto = "thin"
opt-level = 2
