name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk-3-dev libjack-jackd2-dev liblzma5 libsndfile1 
        version: 1.0
    - name: List installed libsndfile shared libraries and links
      run: ls -l /usr/lib/x86_64-linux-gnu/libsndfile*
    - name: Create link for libsndfile.so
      run: sudo find /usr/lib/x86_64-linux-gnu/ -type f -name "libsndfile.so.*" -exec ln -s {} /usr/lib/x86_64-linux-gnu/libsndfile.so \;
    - name: Build
      run: cargo build --verbose --release
#    - name: Run tests
#      run: cargo test --verbose
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: riff-daw
        path: ./target/release/riff-daw
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: vst-checker
        path: ./target/release/vst-checker
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: clap-checker
        path: ./target/release/clap-checker
